gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_finger_middle_joint_1
    - robotiq_finger_middle_joint_2
    - robotiq_finger_middle_joint_3
    - robotiq_finger_1_joint_1
    - robotiq_finger_1_joint_2
    - robotiq_finger_1_joint_3
    - robotiq_finger_2_joint_1
    - robotiq_finger_2_joint_2
    - robotiq_finger_2_joint_3
  gains:
    robotiq_finger_middle_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_middle_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_middle_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_1_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_1_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_1_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_2_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_2_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_2_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_mode_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_palm_finger_1_joint
    - robotiq_palm_finger_2_joint
  gains:
    robotiq_palm_finger_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_palm_finger_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
    shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
    elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    wrist_1_joint: {p: 125,  d: 10, i: 10, i_clamp: 1}
    wrist_2_joint: {p: 125,  d: 10, i: 10, i_clamp: 1}
    wrist_3_joint: {p: 39,  d: 4.5, i: 5, i_clamp: 1} 
    # shoulder_pan_joint:
    #   p: 2095
    #   d: 153
    #   i: 100.0
    #   i_clamp: 1
    # shoulder_lift_joint:
    #   p: 2090
    #   d: 183
    #   i: 100
    #   i_clamp: 1
    # elbow_joint:
    #   p: 2100
    #   d: 143
    #   i: 100
    #   i_clamp: 1
    # wrist_1_joint:
    #   p: 125
    #   d: 10
    #   i: 10
    #   i_clamp: 1
    # wrist_2_joint:
    #   p: 125
    #   d: 10
    #   i: 10
    #   i_clamp: 1
    # wrist_3_joint:
    #   p: 39
    #   d: 4.5
    #   i: 5
    #   i_clamp: 1
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 100
    action_monitor_rate: 10